spring:
  datasource:
    url: jdbc:mysql://localhost:3306/develhopetest
    username: root
    password: qwerty12345678910#
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
